logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.187.129 # rabbitmq的ip地址
    port: 5672 # rabbitmq服务的端口号
    username: itcast
    password: 123321
    virtual-host: /